---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dexidp.fullname" . }}
  labels:
    app.kubernetes.io/component: dexidp
    {{- include "dexidp.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              argocd.deployment/type: server
      ports:
        - port: {{ .Values.service.ports.http.port }}
          protocol: TCP
        - port: {{ .Values.service.ports.grpc.port }}
          protocol: TCP
    - from:
        - namespaceSelector: {}
      ports:
        - port: {{ .Values.service.ports.metrics.port }}
          protocol: TCP
  podSelector:
    matchLabels:
      argocd.deployment/type: dexidp
  policyTypes:
    - Ingress