---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "dexidp.fullname" . }}
  labels:
    app.kubernetes.io/component: dexidp
    {{- include "dexidp.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-{{ include "dexidp.fullname" . }}
  labels:
    app.kubernetes.io/component: dexidp
    {{- include "dexidp.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-{{ include "dexidp.fullname" . }}
  labels:
    app.kubernetes.io/component: dexidp
    {{- include "dexidp.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-{{ include "dexidp.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ include "dexidp.fullname" . }}