{{- $labels1 := include "argocd.labels" . -}}
{{- $labels2 := include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) -}}
{{- $annotations := include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) -}}
{{- range $repo := .Values.argocd.repos }}
--- # --------------------------------- {{ $repo.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo.name | quote }}
  labels:
    argocd.argoproj.io/secret-type: repository
    {{- $labels1 | nindent 4 }}
    {{- $labels2 | nindent 4 }}
  annotations:
    {{- $annotations | nindent 4 }}
type: Opaque
{{- with $repo.stringData }}
stringData: 
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- with $repo.data }}
data: 
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}