---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "server.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
spec:
  ingress:
    - {}
  podSelector:
    matchLabels:
      argocd.deployment/type: server
  policyTypes:
    - Ingress