---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "redis.fullname" . }}
  labels:
    app.kubernetes.io/component: redis
    {{- include "redis.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-{{ include "redis.fullname" . }}
  labels:
    app.kubernetes.io/component: redis
    {{- include "redis.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - argocd-redis
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-{{ include "redis.fullname" . }}
  labels:
    app.kubernetes.io/component: redis
    {{- include "redis.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-{{ include "redis.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ include "redis.fullname" . }}