---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "notificationscontroller.fullname" . }}
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "notificationscontroller.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels .Values.service.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations .Values.service.annotations) ) | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: {{ .Values.service.ports.metrics.port }}
          protocol: TCP
  podSelector:
    matchLabels:
      argocd.deployment/type: notifications-controller
  policyTypes:
    - Ingress