---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "notificationscontroller.fullname" . }}
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "notificationscontroller.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-{{ include "notificationscontroller.fullname" . }}
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "notificationscontroller.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - {{ include "notificationscontroller.fullname" . }}-cm
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - {{ include "notificationscontroller.fullname" . }}-secret
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-{{ include "notificationscontroller.fullname" . }}
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "notificationscontroller.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-{{ include "notificationscontroller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ include "notificationscontroller.fullname" . }}