{{- if (lookup "v1" "Secret" .Release.Namespace "argocd-notifications-secret") }}
  {{- fail "An 'argocd-notifications-secret' configmap/secret does already exist. Currently it is not supported to use other configmap/secret -names than 'argocd-notifications-secret'" -}}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata: {{/* The name of the configmap has to be static, since the name of the configmap is static in the sourcecode of argocd as well... */}}
  name: argocd-notifications-secret
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "notificationscontroller.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
type: Opaque
{{- with .Values.notification.auth }}
stringData:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}