{{- if not (lookup "v1" "Secret" .Release.Namespace "argocd-redis-auth" | quote )) }}
--- # --------------------------------------------------------------------------------- Secret
apiVersion: v1
kind: Secret
metadata:
  name: argocd-redis-auth
  labels:
    app.kubernetes.io/component: redis
    {{- include "redis.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
  {{- if not .Values.redis.auth }}
  finalizers: 
    - devops-germany.saabgroup.com/keep-me
  {{- end }}
type: Opaque
data:
{{- if .Values.redis.auth }}
  REDIS_PASSWORD: {{ .Values.redis.auth | b64enc | quote  }}
{{- else }}
  REDIS_PASSWORD: {{ (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- end }}