---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "reposerver.fullname" . }}
  labels:
    app.kubernetes.io/component: repo-server
    {{- include "reposerver.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
automountServiceAccountToken: true