{{- if .Values.backup.persistence.enabled -}}
--- # --------------------------------------------------------------------------------- PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
metadata:
  name: {{ include "vaultwarden.fullname" . }}-backup
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels .Values.ingress.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations .Values.ingress.annotations) ) | nindent 4 }}
spec:
  {{- with .Values.backup.persistence.accessModes}}
  accessModes:
    {{- . | toYaml | nindent 4 }}
  {{- end }}  
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size | quote }}
  {{- include "common.storage.class" (dict "pvc" .Values.backup.persistence "global" .Values.global) | nindent 2 }}
  {{- with .Values.backup.persistence.volumeName }}
  volumeName: {{ . | quote }}
  {{- end }}
{{- end -}}