name: CREATE NEW CHART INDEX

on:
  push:
    branches:
      - input
    paths-ignore:
      - '.devcontainer/**'
      - 'README.md'

jobs:
  helm:
    runs-on: ubuntu-latest
    env:
      HELM_URL: https://jnnkrdb.github.io/helm/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Template
        run: helm repo index --url $HELM_URL .

      - name: Upload to master
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "added helmchart changes"
          git push -f origin master